# Generated by Django 2.0.3 on 2021-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_info',
            name='usr_id',
            field=models.IntegerField(default=57, primary_key=True, serialize=False, unique=True),
        ),
    ]
